from pathlib import Path
import struct
from typing import Dict, Iterable, Tuple

import numpy as np
from Bio import SeqIO


ABIF_MAGIC = b"ABIF"
ABIF_VERSION = 101
DIR_ENTRY_SIZE = 28

ELEM_BYTE = 1
ELEM_CHAR = 2
ELEM_SHORT = 4
ELEM_PSTRING = 18


def _as_text(value) -> str:
    if isinstance(value, bytes):
        return value.decode("ascii", errors="ignore")
    return str(value)


def _pascal_string(value: str) -> bytes:
    raw = value.encode("ascii", errors="replace")[:255]
    return bytes([len(raw)]) + raw


def _pad4(value: int) -> int:
    return (value + 3) & ~3


def _sample_name(record, source_path: str) -> str:
    raw = record.annotations.get("abif_raw", {}).get("SMPL1")
    if isinstance(raw, bytes):
        # Biopython normally exposes the decoded payload, but tolerate a
        # Pascal-string representation as well.
        if raw and raw[0] == len(raw) - 1:
            return raw[1:].decode("ascii", errors="replace")
        text = raw.decode("ascii", errors="replace").strip("\x00")
        if text:
            return text
    elif raw is not None:
        text = str(raw).strip("\x00")
        if text:
            return text
    return Path(source_path).stem


def _get_trace_channels(abif_raw: Dict) -> Tuple[str, Dict[str, np.ndarray]]:
    order = _as_text(abif_raw.get("FWO_1", "GATC")).strip("\x00").upper()
    if len(order) < 4 or any(base not in "ACGT" for base in order[:4]):
        order = "GATC"
    order = order[:4]

    traces: Dict[str, np.ndarray] = {}
    for base, tag in zip(order, ("DATA9", "DATA10", "DATA11", "DATA12")):
        if tag not in abif_raw:
            raise ValueError(f"Missing required AB1 trace tag: {tag}")
        traces[base] = np.asarray(abif_raw[tag], dtype=np.int16)

    lengths = {len(values) for values in traces.values()}
    if len(lengths) != 1:
        raise ValueError("AB1 trace channels DATA9..DATA12 have different lengths")
    if not lengths or next(iter(lengths)) == 0:
        raise ValueError("AB1 trace channels are empty")

    return order, traces


def _trace_bounds(peaks: np.ndarray, start: int, end: int, trace_length: int) -> Tuple[int, int]:
    """
    Convert a base interval [start, end) into a trace interval [left, right).

    Internal boundaries are placed halfway between adjacent called peaks. This
    preserves the complete local peak shape for the retained first/last base
    while removing the discarded neighboring signal.
    """
    if start <= 0:
        left = 0
    else:
        left = int((int(peaks[start - 1]) + int(peaks[start])) // 2)

    if end >= len(peaks):
        right = trace_length
    else:
        right = int((int(peaks[end - 1]) + int(peaks[end])) // 2 + 1)

    left = max(0, min(left, trace_length - 1))
    right = max(left + 1, min(right, trace_length))
    return left, right


def _build_items(
    order: str,
    traces: Dict[str, np.ndarray],
    sequence: str,
    peak_positions: Iterable[int],
    qualities: Iterable[int],
    sample_name: str,
):
    items = []

    # DATA9..DATA12 follow the original FWO_1 order.
    for base, tag_number in zip(order, (9, 10, 11, 12)):
        arr = np.asarray(traces[base], dtype=">i2")
        items.append(
            (b"DATA", tag_number, ELEM_SHORT, 2, len(arr), arr.tobytes())
        )

    items.append((b"FWO_", 1, ELEM_CHAR, 1, 4, order.encode("ascii")))

    calls = sequence.encode("ascii", errors="replace")
    items.append((b"PBAS", 1, ELEM_CHAR, 1, len(calls), calls))
    items.append((b"PBAS", 2, ELEM_CHAR, 1, len(calls), calls))

    peaks = np.asarray(list(peak_positions), dtype=">u2")
    items.append((b"PLOC", 1, ELEM_SHORT, 2, len(peaks), peaks.tobytes()))
    items.append((b"PLOC", 2, ELEM_SHORT, 2, len(peaks), peaks.tobytes()))

    quality_bytes = bytes(max(0, min(int(q), 255)) for q in qualities)
    # Biopython AbiIO expects PCON2 to be a CHAR payload and decodes it.
    # Writing it as ABIF BYTE makes AbiIO return a tuple, which then fails
    # with: 'tuple' object has no attribute 'decode'.
    items.append(
        (b"PCON", 1, ELEM_CHAR, 1, len(quality_bytes), quality_bytes)
    )
    items.append(
        (b"PCON", 2, ELEM_CHAR, 1, len(quality_bytes), quality_bytes)
    )

    sample = _pascal_string(sample_name)
    items.append((b"SMPL", 1, ELEM_PSTRING, 1, len(sample), sample))

    comment = _pascal_string("Predicted trim generated by unet-pytorch")
    items.append((b"CMNT", 1, ELEM_PSTRING, 1, len(comment), comment))

    return items


def _write_abif(output_path: str, items) -> None:
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    header_size = 128
    data_offsets = []
    current_offset = header_size

    for _, _, _, _, _, data in items:
        if len(data) <= 4:
            data_offsets.append(None)
        else:
            data_offsets.append(current_offset)
            current_offset += _pad4(len(data))

    directory_offset = current_offset
    directory_size = len(items) * DIR_ENTRY_SIZE

    with output.open("wb") as handle:
        handle.write(ABIF_MAGIC)
        handle.write(struct.pack(">H", ABIF_VERSION))

        handle.write(
            struct.pack(
                ">4sIHHIII4s",
                b"tdir",
                1,
                1023,
                DIR_ENTRY_SIZE,
                len(items),
                directory_size,
                directory_offset,
                b"\x00" * 4,
            )
        )
        handle.write(b"\x00" * (header_size - handle.tell()))

        for offset, item in zip(data_offsets, items):
            data = item[5]
            if offset is None:
                continue
            if handle.tell() != offset:
                raise RuntimeError(
                    f"ABIF data offset mismatch: expected {offset}, got {handle.tell()}"
                )
            handle.write(data)
            padding = _pad4(len(data)) - len(data)
            if padding:
                handle.write(b"\x00" * padding)

        if handle.tell() != directory_offset:
            raise RuntimeError(
                "ABIF directory offset mismatch while writing trimmed file"
            )

        for offset, item in zip(data_offsets, items):
            tag_name, tag_number, elem_type, elem_size, num_elements, data = item
            data_size = len(data)

            if data_size <= 4:
                inline = data + b"\x00" * (4 - data_size)
                offset_or_data = struct.unpack(">I", inline)[0]
            else:
                offset_or_data = int(offset)

            handle.write(
                struct.pack(
                    ">4sIHHIII4s",
                    tag_name,
                    tag_number,
                    elem_type,
                    elem_size,
                    num_elements,
                    data_size,
                    offset_or_data,
                    b"\x00" * 4,
                )
            )


def write_trimmed_ab1(
    source_path: str,
    output_path: str,
    start: int,
    end: int,
) -> str:
    """
    Write the predicted called-base interval [start, end) as a new AB1 file.

    The output contains cropped real DATA9..DATA12 trace channels, rebased
    PLOC1/2 peak positions, cropped PBAS1/2 base calls and PCON1/2 quality
    values. The original AB1 is never modified.
    """
    source = Path(source_path)
    record = SeqIO.read(str(source), "abi")
    sequence = str(record.seq).upper()
    n = len(sequence)

    if not (0 <= start < end <= n):
        raise ValueError(
            f"Invalid predicted interval [{start}, {end}) for AB1 length {n}"
        )

    abif_raw = record.annotations.get("abif_raw", {})
    peaks = np.asarray(
        abif_raw.get("PLOC2", abif_raw.get("PLOC1", [])),
        dtype=np.int64,
    )
    if len(peaks) < n:
        raise ValueError(
            f"AB1 has {n} base calls but only {len(peaks)} peak locations"
        )
    peaks = peaks[:n]

    order, traces = _get_trace_channels(abif_raw)
    trace_length = len(next(iter(traces.values())))
    left, right = _trace_bounds(peaks, start, end, trace_length)

    trimmed_traces = {
        base: np.asarray(values[left:right], dtype=np.int16)
        for base, values in traces.items()
    }
    trimmed_peaks = (peaks[start:end] - left).astype(np.int64)
    if np.any(trimmed_peaks < 0) or np.any(trimmed_peaks > 65535):
        raise ValueError("Trimmed AB1 peak positions cannot be represented as uint16")

    qualities = list(
        record.letter_annotations.get("phred_quality", [0] * n)
    )
    if len(qualities) < n:
        qualities.extend([0] * (n - len(qualities)))

    trimmed_sequence = sequence[start:end]
    trimmed_qualities = qualities[start:end]

    items = _build_items(
        order=order,
        traces=trimmed_traces,
        sequence=trimmed_sequence,
        peak_positions=trimmed_peaks,
        qualities=trimmed_qualities,
        sample_name=f"{_sample_name(record, str(source))}_trimmed",
    )
    output = Path(output_path)
    try:
        _write_abif(str(output), items)

        # Parse our own output immediately. If the generated AB1 is malformed,
        # remove the partial output instead of leaving a broken chromatogram.
        written = SeqIO.read(str(output), "abi")
        if len(written) != len(trimmed_sequence):
            raise RuntimeError(
                f"Trimmed AB1 validation failed: expected {len(trimmed_sequence)} "
                f"bases, parsed {len(written)}"
            )
    except Exception:
        try:
            output.unlink(missing_ok=True)
        except OSError:
            pass
        raise

    return str(output)
